# __________ buffer Parameters __________
buffer_length: 1000
env_batch_size: 128

# __________ Training Parameters __________
batch_size: 2048
num_epochs: 10
eval_interval: 5000   
eval_episodes: 30  
save_interval: 2000
log_interval: 1
discount_factor: 0.99

# __________ Agent Parameters __________
initial_adaptive_kl_beta: 1.0
adaptive_kl_tolerance: 0.01
kl_cutoff_factor: 0.0
adaptive_kl_target: 0.01

# The following parameters can be changed during training
policy_l2_reg: 0.0
value_function_l2_reg: 0.0
shared_vars_l2_reg: 0.0
value_pred_loss_coef: 0.05
entropy_regularization: 0.005
learning_rate: 0.000001
